export const FETCH_ABOUT = 'FETCH_ABOUT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const UPDATE_VALUE = 'UPDATE_VALUE';
export const LOCATION_SUGGEST = 'LOCATION_SUGGEST';
export const UPDATE_UI_DATA = 'UPDATE_UI_DATA';
export const EVENT_REQUEST = 'EVENT_REQUEST';
export const EVENT_SUCCESS = 'EVENT_SUCCESS';
export const EVENT_FAILURE = 'EVENT_FAILURE';
// global
export const LOAD_AUTHENTICATION_DATA = 'LOAD_AUTHENTICATION_DATA';
// post event info
export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';
// get event location suggest
export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAILURE = 'LOCATION_FAILURE';
// get event location suggest
export const LOCATION_CREATE_REQUEST = 'LOCATION_CREATE_REQUEST';
export const LOCATION_CREATE_SUCCESS = 'LOCATION_CREATE_SUCCESS';
export const LOCATION_CREATE_FAILURE = 'LOCATION_CREATE_FAILURE';
// get event type
export const EVENTTYPE_REQUEST = 'EVENTTYPE_REQUEST';
export const EVENTTYPE_SUCCESS = 'EVENTTYPE_SUCCESS';
export const EVENTTYPE_FAILURE = 'EVENTTYPE_FAILURE';
// get event topic
export const EVENTTOPIC_REQUEST = 'EVENTTOPIC_REQUEST';
export const EVENTTOPIC_SUCCESS = 'EVENTTOPIC_SUCCESS';
export const EVENTTOPIC_FAILURE = 'EVENTTOPIC_FAILURE';
// get country
export const COUNTRY_REQUEST = 'COUNTRY_REQUEST';
export const COUNTRY_SUCCESS = 'COUNTRY_SUCCESS';
export const COUNTRY_FAILURE = 'COUNTRY_FAILURE';
// get city
export const CITY_REQUEST = 'CITY_REQUEST';
export const CITY_SUCCESS = 'CITY_SUCCESS';
export const CITY_FAILURE = 'CITY_FAILURE';
// register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
// events for admin's approving
export const ALLEVENT_REQUEST = 'ALLEVENT_REQUEST';
export const ALLEVENT_SUCCESS = 'ALLEVENT_SUCCESS';
export const ALLEVENT_FAILURE = 'ALLEVENT_FAILURE';
// approve event
export const APPROVEEVENT_REQUEST = 'APPROVEEVENT_REQUEST';
export const APPROVEEVENT_SUCCESS = 'APPROVEEVENT_SUCCESS';
export const APPROVEEVENT_FAILURE = 'APPROVEEVENT_FAILURE';
// user
export const ALLUSER_REQUEST = 'ALLUSER_REQUEST';
export const ALLUSER_SUCCESS = 'ALLUSER_SUCCESS';
export const ALLUSER_FAILURE = 'ALLUSER_FAILURE';
// publish event for approve
export const PUBLISHEVENT_REQUEST = 'PUBLISHEVENT_REQUEST';
export const PUBLISHEVENT_SUCCESS = 'PUBLISHEVENT_SUCCESS';
export const PUBLISHEVENT_FAILURE = 'PUBLISHEVENT_FAILURE';
// event info for preview mode
export const PREVIEW_MODE_REQUEST = 'PREVIEW_MODE_REQUEST';
export const PREVIEW_MODE_SUCCESS = 'PREVIEW_MODE_SUCCESS';
// BACK FROM PREVIEW MODE TO CONTINUE EDITTING
export const BACK_FROM_PREVIEW_REQUEST = 'BACK_FROM_PREVIEW_REQUEST';
export const BACK_FROM_PREVIEW_SUCCESS = 'BACK_FROM_PREVIEW_SUCCESS';
//
export const HOBBY_REQUEST = 'HOBBY_REQUEST';
export const HOBBY_SUCCESS = 'HOBBY_SUCCESS';
export const HOBBY_FAILURE = 'HOBBY_FAILURE';
//
export const CLEAR_GUEST = 'CLEAR_GUEST';
//
export const USER_EVENTS_MANAGEMENT_REQUEST = 'USER_EVENTS_MANAGEMENT_REQUEST';
export const USER_EVENTS_MANAGEMENT_SUCCESS = 'USER_EVENTS_MANAGEMENT_SUCCESS';
export const USER_EVENTS_MANAGEMENT_FAIL = 'USER_EVENTS_MANAGEMENT_FAIL';
export const TYPE_CHANGED = 'TYPE_CHANGED';
export const CREATE_EVALUATE_REQUEST = 'CREATE_EVALUATE_REQUEST';
export const CREATE_EVALUATE_SUCCESS = 'CREATE_EVALUATE_SUCCESS';
export const CREATE_EVALUATE_FAIL = 'CREATE_EVALUATE_FAIL';
export const TICKET_SELECTED = 'TICKET_SELECTED';
export const CHECK_OUT_REQUEST = 'CHECK_OUT_REQUEST';
export const CHECK_OUT_SUCCESS = 'CHECK_OUT_SUCCESS';
export const CHECK_OUT_FAIL = 'CHECK_OUT_FAIL';
export const SEARCH_HOME_REQUEST = 'SEARCH_HOME_REQUEST';
export const SEARCH_HOME_SUCCESS = 'SEARCH_HOME_SUCCESS';
export const SEARCH_HOME_FAILURE = 'SEARCH_HOME_FAILURE';

export const GET_RECENTLY_EVENTS_REQUEST = 'GET_RECENTLY_EVENTS_REQUEST';
export const GET_RECENTLY_EVENTS_SUCCESS = 'GET_RECENTLY_EVENTS_SUCCESS';
export const GET_RECENTLY_EVENTS_FAILURE = 'GET_RECENTLY_EVENTS_FAILURE';

export const GET_POPULAR_EVENTS_REQUEST = 'GET_POPULAR_EVENTS_REQUEST';
export const GET_POPULAR_EVENTS_SUCCESS = 'GET_POPULAR_EVENTS_SUCCESS';
export const GET_POPULAR_EVENTS_FAILURE = 'GET_POPULAR_EVENTS_FAILURE';

export const CAROUSEL_RECENTLY_EVENTS_BACK = 'CAROUSEL_RECENTLY_EVENTS_BACK';
export const CAROUSEL_RECENTLY_EVENTS_NEXT = 'CAROUSEL_RECENTLY_EVENTS_NEXT';
export const CAROUSEL_POPULAR_EVENTS_BACK = 'CAROUSEL_POPULAR_EVENTS_BACK';
export const CAROUSEL_POPULAR_EVENTS_NEXT = 'CAROUSEL_POPULAR_EVENTS_NEXT';

//
export const EVENT_MANAGEMENT_POPUP_REJECT_OPENED =
  'EVENT_MANAGEMENT_POPUP_REJECT_OPENED';
export const EVENT_MANAGEMENT_POPUP_REJECT_CLOSED =
  'EVENT_MANAGEMENT_POPUP_REJECT_CLOSED';
export const EVENT_MANAGEMENT_REJECT_CONFIRMED =
  'EVENT_MANAGEMENT_REJECT_CONFIRMED';
export const EVENT_MANAGEMENT_REJECT_SUCCESS =
  'EVENT_MANAGEMENT_REJECT_SUCCESS';
export const EVENT_MANAGEMENT_REJECT_FAILURE =
  'EVENT_MANAGEMENT_REJECT_FAILURE';

//

export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';
export const GUEST_CHECK_OUT = 'GUEST_CHECK_OUT';
export const GUEST_ENTER = 'GUEST_ENTER';
export const OUT_OF_TICKET = 'OUT_OF_TICKET';
export const LOAD_TICKETS = 'LOAD_TICKETS';
export const NOTIFICATION_SEEN_REQUEST = 'NOTIFICATION_SEEN_REQUEST';
export const NOTIFICATION_SEEN_SUCCESS = 'NOTIFICATION_SEEN_SUCCESS';
export const NOTIFICATION_SEEN_FAILURE = 'NOTIFICATION_SEEN_FAILURE';
export const CHANGE_LANG = 'CHANGE_LANG';
export const TOGGLE = 'TOGGLE';
export const GUEST_INFO_REQUEST = 'GUEST_INFO_REQUEST';
export const GUEST_INFO_SUCCESS = 'GUEST_INFO_SUCCESS';
export const GUEST_INFO_FAILURE = 'GUEST_INFO_FAILURE';
//
export const LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST';
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_FAIL = 'LOAD_CURRENT_USER_FAIL';
//
export const UPDATE_GUEST_INFO_INPUT = 'UPDATE_GUEST_INFO_INPUT';
export const ALLEVENT_SUPERADMIN_REQUEST = 'ALLEVENT_SUPERADMIN_REQUEST';
export const ALLEVENT_SUPERADMIN_SUCCESS = 'ALLEVENT_SUPERADMIN_SUCCESS';
export const ALLEVENT_SUPERADMIN_FAIL = 'ALLEVENT_SUPERADMIN_FAIL';

//Admin
export const ADMIN_USER_DETAIL_REQUEST = 'ADMIN_LOAD_USER_DETAIL_REQUEST';
export const ADMIN_USER_DETAIL_SUCCESS = 'ADMIN_LOAD_USER_DETAIL_SUCCESS';
export const ADMIN_USER_DETAIL_FAIL = 'ADMIN_LOAD_USER_DETAIL_FAIL';
